# Generated by Django 4.1.7 on 2023-04-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_blockchain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blockchain',
        ),
    ]
