# Generated by Django 4.1.7 on 2023-04-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_greener_rename_point_composter_composter_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='composter',
            old_name='username',
            new_name='orgName',
        ),
    ]
