# Generated by Django 4.1.7 on 2023-04-07 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_rename_username_composter_orgname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greener',
            old_name='point',
            new_name='greener_location',
        ),
    ]
